config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    member do
      get 'showByTag'
    end
    collection do
      post 'search'
      get 'showByMonth'
    end
  end

  match '/blog', :to=>'posts#index'
  match '/create', :to => 'posts#create'
  match '/update', :to => 'posts#update'
  match '/delete', :to => 'posts#destroy'

  resources :resumes
  resources :comments
  resources :notices
  resources :abouts, :only => [:index]

  match '/home', :to => 'abouts#index'

  resources :settings do
    collection do 
      post 'update_intro'
      post 'create_link'
      post 'update_link'
      delete 'destroy_link'
    end
  end

  
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => 'abouts#index'

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

	before_filter :admin_validate, :except => []
	def index
		@intro = Intro.first
		@links = Link.all
	end

	def update_intro
		intro = Intro.first
		if intro.update_attributes({:content => params[:intro][:content]})
			flash[:success] = 'Successfully updated!'
		else
			flash[:error] = 'Error!!!'
		end
		redirect_to settings_path
	end

	def create_link
		if Link.create(:name => params[:link][:name], :url => params[:link][:url])
			flash[:success] = 'Successfully created!'
		else
			flash[:error] = 'Error!!!'
		end
		redirect_to settings_path
	end

	def update_link
		link = Link.find(params[:link][:id])
		if link.update_attributes({:name => params[:link][:name], :url => params[:link][:url]})
			flash[:success] = 'Successfully updated!'
		else
			flash[:error] = 'Error!!!'
		end
		redirect_to settings_path
	end

	def destroy_link
		if Link.delete(params[:id])
			flash[:success] = 'Successfully deleted!'
		else
			flash[:error] = 'Error!!!'
		end
		redirect_to settings_path
	end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/index.html.erb
<div class="top-margin post_feed">

	<!--show intro-->
	<div>
		<%= form_for(:intro, :url => update_intro_settings_path) do |f| %>
		<legend>Introduce</legend>
		<%= f.text_area :content, :value => (@intro? @intro.content : ""), :class => "width-textfield" %>
		<br>
		<%= f.submit "Update", :confirm =>"Update this post?", :class => "btn btn-large btn-primary"%>
		<% end %>
	</div>
	<!--show/update/delete links-->
	<div>
		<legend>All links</legend>
		<% @links.each do |l| %>
			<%= form_for(:link, :url => update_link_settings_path) do |f| %>
			<%= f.hidden_field :id, :value => l.id %>
			<%= f.text_field :name, :value => l.name %>
			<%= f.text_field :url, :value => l.url %>
			<%= link_to l.name, l.url, :target => "view_window" %>
			<%= f.submit "Update", :confirm =>"Update this link?", :class => "btn btn-primary pull-right" %>
			<%= link_to "Delete", "#{destroy_link_settings_path}?id=#{l.id}", :confirm =>"Delete this link?", :method => :delete, :class => "btn btn-primary pull-right" %>
			<br>
			<% end %>
		<% end %>
	</div>
	<!--add link-->
	<div>
		<legend>Add a link</legend>
		<%= form_for(:link, :url => create_link_settings_path) do |f| %>
			<%= f.text_field :name %>
			<%= f.text_field :url %>
			<%= f.submit "Create", :confirm =>"Create this link?", :class => "btn btn-primary pull-right" %>
			<br>
		<% end %>
	</div>
</div>