config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    member do
      get 'showByTag'
    end
    collection do
      post 'search'
      get 'showByMonth'
    end
  end

  match '/blog', :to=>'posts#index'
  match '/create', :to => 'posts#create'
  match '/update', :to => 'posts#update'
  match '/delete', :to => 'posts#destroy'

  resources :resumes
  resources :comments
  resources :notices
  resources :abouts, :only => [:index]

  match '/home', :to => 'abouts#index'

  resources :settings do
    collection do 
      post 'update_intro'
      post 'create_link'
      post 'update_link'
      delete 'destroy_link'
    end
  end

  
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => 'abouts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :title, :content
	has_and_belongs_to_many :tags
	has_many :comments, :dependent => :delete_all
	has_many :notices, :through => :comments

	def pre_post
		Post.where("id < ?", self.id).order("id DESC").first
	end

	def next_post
		Post.where("id > ?", self.id).order("id ASC").first
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :admin_validate, :only => [:new, :create, :edit, :update, :destroy]
	respond_to :html, :xml, :json

	def index
		@intro = Intro.first
		@links = Link.all
		@posts = Post.paginate(:page => params[:page], :per_page => 10, :order => 'updated_at DESC')
		@posts_years = Post.all.group_by {|post| post.created_at.beginning_of_year}
	end

	def show
		@post = Post.find params[:id]
		@comment = Comment.new
	end

	def search
		@keyword = params[:keyword]
		@posts = Post.paginate(:conditions => ["content LIKE ? or title LIKE ?", "%#{@keyword}%", "%#{@keyword}%"], :page => params[:page], :per_page => 10)
	end

	def showByMonth
		@month = Date.parse params[:month]
		sql = "select *
		from posts
		where created_at >= '#{@month.beginning_of_month}' and  
		created_at < '#{@month.next_month.beginning_of_month}'
		"
		#@posts = Post.find_by_sql(sql)
		@posts = Post.paginate_by_sql(sql, :page => params[:page], :per_page => 10)
		#@posts = Post.all.select { |post| post.created_at.beginning_of_month == params[:month]}
	end

	def showByTag
		@tag = Tag.find params[:id.to_s]
		@posts = @tag.posts.paginate(:page => params[:page], :per_page => 10, :order => 'updated_at DESC')
	end

	def edit
		@post = Post.find params[:id]
		@tags = @post.tags
		@all_tags = Tag.all
	end

	def update
		post = Post.find params[:post][:id]
		if Post.update(post.id, :title => params[:post][:title], :content => params[:post][:content])
			tags = params[:post][:tags].split(/,/)
			post.tags.each do |t|
				if tags.include? t.name
					tags.delete t.name
				else
					post.tags.delete t
					if t.posts.empty?
						Tag.delete t.id
					end
				end
			end
			if tags
				tags.each do |t|
					tag = Tag.find_by_name t
					unless tag
						tag = Tag.new(:name => t)
						tag.save
					end
					post.tags<<tag
				end
			end
			flash[:success] = 'Successfully saved!'
			redirect_to post_path(post)
		else
			render 'edit'
		end
	end

	def new
		@tags = Tag.all
	end

	def create
		post = Post.new
		post.title = params[:post][:title]
		post.content = params[:post][:content]
		tags = params[:post][:tags].split(/,/)
		
		tags.each do |t|
			if !t.blank?
				tag = Tag.find_by_name t
				unless tag
					tag = Tag.new(:name => t)
					tag.save
				end
				post.tags<<tag
			end
		end
		
		if post.save
			flash[:success] = 'Successfully posted!'
			redirect_to post_path(post)
		else
			render 'new'
		end
	end

	def destroy
		id = params[:id]
		post = Post.find id
		tags = post.tags
		notices = post.notices
		notices.each do |n|
			Notice.delete n.id
		end
		tags.each do |t|
			if t.posts.size == 1
				Tag.delete t.id
			end
		end
		if post.destroy
			flash[:success] = 'Successfully deleted!'
			redirect_to posts_path
		else
			render 'destroy'
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_show_posts.html.erb
<% if !posts.empty? %>
	<% posts.each do |post| %>

	<!--feed-->
	<div class="post_feed" id="post">
		<!--title-->
		<div class="post-header">
			<h2><%= link_to post.title, post, :class=>"post-title" %></h2>
		</div>
		<!--date-->
		<div class="post-ts-flag">
			<div class="post-ts-date-flag">
				<span><%= post.created_at.strftime("%b %d") %></span>
			</div>
		</div>
		<!--content-->
		<div class="post-content">
			<p><%= raw post.content.first(1000)  %></p>
		</div>
		<!--footer for post-->
		<div id="post-footer">
			<div class="post-footer"></div>
			<div class="post-footer-tags">
				<% post.tags.each do |tag| %>
				<a class="label" href=<%= showByTag_post_path tag %>><%= tag.name %></a>
				<% end %>
			</div>
			<div class="post-footer-coms small-size" >
				<% if signed_in? %>
				<a class="muted" href=<%= edit_post_path post %>><i class="icon-text-height"></i> Edit</a>
				<i class="icon-trash"></i><%= link_to " Delete", delete_path+"?id="+post.id.to_s, :confirm => "Delete this post?", :class => "muted" %>
				<% end %>
				<% if post.comments.size == 0 %>
				<a class="muted" href=<%= post_path post %>><i class="icon-edit"></i> Leave a comment</a>
				<% else %>
				<a class="muted" href=<%= post_path post %>><i class="icon-list-alt"></i><%= " Comments: "+post.comments.size.to_s %></a>
				<% end %>
			</div>
		</div>
	</div>
	<% end %>
<% else %>
	<div class="alert alert-block">
		<h3>Sorry,</h3>
		<p>Couldn't find anything to display...</p>
	</div>
<% end %>

app/views/posts/edit.html.erb
<div class="top-margin">
	<!--display the post-->
	<div id="post" class="post_feed">
		<h2>Edit this post</h2>
		<%= form_for(:post, :url => update_path) do |f| %>
			<%= f.hidden_field :id, :value => @post.id.to_s %>
			<%= f.label :title, "Title:"%>
			<%= f.text_field :title, :value => @post.title, :class=>"width-textfield" %>

			<%= f.label :content, "Content:" %>
			<%= f.cktext_area :content, :value => @post.content, :class=>"width-textfield tinymce" %><br>

			<% str_tag = "" %>
			<% @tags.each do |t| %>
				<% str_tag = str_tag.blank? ? t.name : "#{str_tag},#{t.name}" %>
			<% end %>
			
			<%= f.label :tags, "Tags:" %>
			<%= f.text_field :tags, :id => "tags", :value => str_tag, :class=>"width-textfield" %><br>

			<% @all_tags.each do |t| %>
				<a class="label normal-size addTag"><%= "#{t.name}" %></a>
			<% end %>
			<br>
			<br>
			<br>
			<%= f.submit "Update", :confirm =>"Update this post?", :class => "btn btn-large btn-primary" %>
			<%= link_to "Cancel", post_path(@post), :confirm =>"Give up this post?", :class=> "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/posts/index.html.erb
<% content_for :where do %>
	<%= "blog" %>
<% end %>
<% content_for :title do %>
	<%= "| Blog" %>
<% end %>
<div class="top-margin">
	<div class="container-fluid">
		<div class="row-fluid">

			<!--left container-->
			<div class="span10">
				<!--show posts-->
				<%= render :partial => "show_posts", :locals => {:posts => @posts} %>
				<!-- pager -->
				<div class="apple_pagination">
				    <%= will_paginate @posts, :container => false %>
				</div>
			</div>

			<!--right container-->
			<div class="span2">

				<!--right accordion sider-->
				<div class="accordion side" id="right_accordion">
					<!--about me-->
					<div class="accordion-group">
						<div class="accordion-heading post-sider">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#right_accordion" href="#collapseOne">
								<i class="icon-user icon-white"></i><span>About Me</span>
							</a>
						</div>
						<div id="collapseOne" class="accordion-body collapse in">
							<div class="accordion-inner">
								<% if @intro %>
								<p><%= @intro.content %></p>
								<% else %>
								<p>Welcome to my blog!</p>
								<% end %>
							</div>
						</div>
					</div>
					<!--tags-->
					<div class="accordion-group">
						<div class="accordion-heading post-sider">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#right_accordion" href="#collapseTwo">
								<i class="icon-tags icon-white"></i><span>Tags</span>
							</a>
						</div>
						<div id="collapseTwo" class="accordion-body collapse">
							<div class="accordion-inner" id="tagscloud">
								<% tags=Tag.all.each do |tag| %>
									<a class="label" href=<%= showByTag_post_path tag %>><%= "#{tag.name} (#{tag.posts.size})" %></a>
								<% end %>
							</div>
						</div>
					</div>
					<!--archive:date-->
					<div class="accordion-group">
						<div class="accordion-heading post-sider">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#right_accordion" href="#collapseThree">
								<i class="icon-th-list icon-white"></i><span>Archive</span>
							</a>
						</div>
						<div id="collapseThree" class="accordion-body collapse">
							<div class="accordion-inner archive-inner">
								<div class="accordion" id="date_inner_accordion">
								<% @posts_years.each do |year, posts|%>
									<div class="accordion-group each-year">
										<div class="accordion-heading">
											<a class="accordion-toggle" data-toggle="collapse" data-parent="#date_inner_accordion" href="#collapse"+<%= year.strftime("%Y")%>>
												<%= year.strftime("%Y")%>
											</a>
										</div>
										<div id="collapse"+<%= year.strftime("%Y")%> class="accordion-body collapse in">
											<div class="accordion-inner">
												<ul class="nav nav-list">
													<% posts.group_by { |post| post.created_at.beginning_of_month}.each do |month, post_s| %>
														<li><a href=<%= "#{showByMonth_posts_path}?month=#{month}"%>><%= month.strftime("%B")+"  " %><span class="badge"><%= post_s.size %></span></a></li>
													<% end %>
												</ul>
											</div>
										</div>
									</div>
								<% end %>
								</div>
							</div>
						</div>
					</div>
					<!--links-->
					<div class="accordion-group">
						<div class="accordion-heading post-sider">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#right_accordion" href="#collapseFour">
								<i class="icon-star icon-white"></i><span>Links</span>
							</a>
						</div>
						<div id="collapseFour" class="accordion-body collapse">
							<div class="accordion-inner links-inner">
								<% @links.each do |l| %>
								<%= link_to l.name, l.url, :target => "view_window" %><br>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<div class="top-margin">
	<!--display the post-->
	<div id="post" class="post_feed">
		<h2>Write a post</h2>
		<%= form_for(:post, :url => create_path) do |f| %>
			<%= f.label :title, "Title:"%>
			<%= f.text_field :title, :class=>"width-textfield" %>

			<%= f.label :content, "Content:" %>

			<%= f.cktext_area :content, :class=>"width-textfield", :id=>"new_content" %><br>

			<%= f.label :tags, "Tags:" %>
			<%= f.text_field :tags, :class=>"width-textfield", :id => "tags" %><br>

			<% @tags.each do |t| %>
				<a class="label normal-size addTag"><%= "#{t.name}" %></a>
			<% end %>
			<br>
			<br>
			<br>
			<%= f.submit "Post", :confirm =>"Post?", :class => "btn btn-large btn-primary" %>
			<%= link_to "Cancel", posts_path, :confirm =>"Give up this post?",:class=> "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/posts/search.html.erb
<% content_for :where do %>
	<%= "search" %>
<% end %>
<div class="top-margin">
	<div>
		<h2>Results for keyword "<%= @keyword %>"</a></h2>
	</div>
	<!--show posts-->
	<%= render :partial => "show_posts", :locals => {:posts => @posts} %>
	<!-- pager -->
	<div class="apple_pagination">
		<%= will_paginate @posts, :container => false %>
	</div>
</div>

app/views/posts/show.html.erb
	<% content_for :title do %>
	<%= "| #{@post.title}" %>
	<% end %>
	<% content_for :where do %>
	<%= "#{@post.title} -- #{post_path @post}" %>
	<% end %>
	<!--alert-->
	<div id="show-alert"></div>
	<!--show whole post-->
	<div class="top-margin post_feed" id="whole_show">
		<!--display the post-->
		<div id="post">
			<h2><%= @post.title %></h2>
			<p class="muted small-size"><%= "Posted on "+@post.created_at.to_formatted_s(:long) %></p>
			<p><%= raw @post.content %></p>
			<% if @post.updated_at != @post.created_at %>
			<div>
				<p class="muted small-size"><%= "Last edited on "+@post.updated_at.to_formatted_s(:long) %></p>
			</div>
			<% end %>
			<div id="post-footer">
				<div class="post-footer-tags">
					<% @post.tags.each do |tag| %>
					<a class="label normal-size" href=<%= showByTag_post_path tag %>><%= tag.name %></a>
					<% end %>
				</div>
				<div class="post-footer-coms normal-size" >
					<% if signed_in? %>
					<a class="muted" href=<%= edit_post_path @post %>><i class="icon-text-height"></i> Edit</a>
					<i class="icon-trash"></i><%= link_to " Delete", delete_path+"?id="+@post.id.to_s, :confirm => "Delete this post?", :class => "muted" %>
					<% end %>
				</div>
			</div>
			<div class="top-margin-small"></div>
			<div id="next-prev">
				<br>
				<hr>
				<p>
					<span class="muted">Previous post: </span>
					<% pre=@post.pre_post %>
					<% if pre %>
					<%= link_to pre.title, pre %>
					<% else %>
					This is the first post.
					<% end %>
				</p>
				<p>
					<span class="muted">Next post: </span>
					<% nxt=@post.next_post %>
					<% if nxt %>
					<%= link_to nxt.title, nxt %>
					<% else %>
					This is the latest post.
					<% end %>
				</p>
			</div>
		</div>

		<!--reply-->
		<div class="top-margin-small" id="reply">
			<legend class="muted">Leave a comment:</legend>
			<div id="comment-error-message"></div>
			<div>
				<%= form_for @comment, :remote => true, :method => :post do |f| %>
				<%= f.label :author, "Name:" %>
				<%= f.text_field :author, :id => "comment_author", :value=>"", :placeholder => "Anonymous", :class=>"width-textfield" %>
				<%= f.label :content, "Comment:" %>
				<%= f.text_area :content, :id => "comment_content", :placeholder => "Please input your comment.", :class=>"width-textarea" %>
				<%= f.hidden_field :post_id, :id => "comment_post_id", :value=>@post.id %>
				<br />
				<%= f.submit "Submit", :class=>"btn", :id => "submit-comment"%>
				<% end %>
			</div>
		</div>

		<!--dislay comments-->
		<div class="top-margin-small" id="comments">
			<!--show all comments-->
			<%= render :partial => "comments/show_comment", :locals => {:post => @post} %>
		</div>

		<!--the next and previous buttons-->
		<% if nxt %>
		<div id="toNext" class="next-button">
			<input type="hidden" id="toNextHidden" value=<%="#{nxt.id}"%>/>
			<div class="to-next-img">
			</div>
		</div>
		<% end %>

		<% if pre %>
		<div id="toPrev" class="prev-button">
			<input type="hidden" id="toPrevHidden" value=<%="#{pre.id}"%>/>
			<div class="to-prev-img">
			</div>
		</div>
		<% end %>

		<!--loading img-->
		<img id="loader" src="/assets/loader.gif" class="loading"/>
	</div>
	
	

app/views/posts/showByMonth.html.erb
<% content_for :where do %>
	<%= "show by month" %>
<% end %>
<div class="top-margin">
	<div>
		<h2>Posts for month "<%= @month.strftime("%B %Y") %>"</a></h2>
	</div>
	<!--show posts-->
	<%= render :partial => "show_posts", :locals => {:posts => @posts} %>
	<!--pager-->
	<div class="apple_pagination">
		<%= will_paginate @posts, :container => false %>
	</div>
</div>

app/views/posts/showByTag.html.erb
<% content_for :where do %>
	<%= "show by tag" %>
<% end %>
<div class="top-margin">
	<div>
		<h2>Results for tag "<%= @tag.name %>"</a></h2>
	</div>
	<!--show posts-->
	<%= render :partial => "show_posts", :locals => {:posts => @posts} %>
	<!--pager-->
	<div class="apple_pagination">
		<%= will_paginate @posts, :container => false %>
	</div>
</div>