config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    member do
      get 'showByTag'
    end
    collection do
      post 'search'
      get 'showByMonth'
    end
  end

  match '/blog', :to=>'posts#index'
  match '/create', :to => 'posts#create'
  match '/update', :to => 'posts#update'
  match '/delete', :to => 'posts#destroy'

  resources :resumes
  resources :comments
  resources :notices
  resources :abouts, :only => [:index]

  match '/home', :to => 'abouts#index'

  resources :settings do
    collection do 
      post 'update_intro'
      post 'create_link'
      post 'update_link'
      delete 'destroy_link'
    end
  end

  
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => 'abouts#index'

end

app/models/resume.rb
class Resume < ActiveRecord::Base
	attr_accessible :name, :content, :show
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController

	before_filter :admin_validate, :only => [:new, :create, :edit, :update, :destroy]

	def index
		@resume = Resume.order("updated_at DESC").where(:show => "t").first()
	end

	def new
		@resume = Resume.new
	end

	def create
		resume = Resume.new(params[:resume])
		if resume.save
			flash[:success] = 'Resume successfully posted!'
			redirect_to resumes_path
		else
			render 'new'
		end
	end

	def edit
		@resume = Resume.find params[:id]
	end

	def update
		resume = Resume.find params[:id]
		if resume.update_attributes(params[:resume])
			flash[:success] = 'Successfully updated!'
			redirect_to resumes_path
		else
			render 'edit'
		end
	end

	def destroy
		if Resume.delete params[:id]
			flash[:success] = 'Successfully deleted!'
			redirect_to resumes_path
		else
			render 'destroy'
		end
	end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/edit.html.erb
</head>
<div class="top-margin">
	<!--display the post-->
	<div id="post" class="post_feed">
		<h2>Edit my resume</h2>
		<%= form_for @resume do |f| %>
			<%= f.label :name, "Name:"%>
			<%= f.text_field :name, :class=>"width-textfield" %>

			<%= f.label :content, "Content:" %>

			<%= f.cktext_area :content, :class=>"width-textfield", :id=>"new_content" %><br>

			<%= f.label :show, "Show:" %>
			<%= f.check_box :show, {:checked => @resume.show} %><br>
			<br>
			<br>
			<br>
			<%= f.submit "Update", :confirm =>"Update?", :class => "btn btn-large btn-primary" %>
			<%= link_to "Cancel", resumes_path, :confirm =>"Give up this resume?",:class=> "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/resumes/index.html.erb
<% content_for :where do %>
	<%= "resume" %>
<% end %>
<% content_for :title do %>
	<%= "| Resume" %>
<% end %>
<div class="top-margin">
	<div class="post_feed">
		<legend>Xiaotong Chen's RESUME</legend>
		<% if @resume %>
		<p><%= raw @resume.content %></p>
		<div>
			<% if signed_in? %>
				<hr>
				<a class="muted" href=<%= edit_resume_path @resume %>><i class="icon-text-height"></i> Edit</a>
				<i class="icon-trash"></i><%= link_to " Delete", @resume, :confirm => "Delete this resume?", :method => :delete, :class => "muted" %>
			<% end %>
		</div>
		<% else %>
		<p>No resume found!</p>
		<% end %>
	</div>
</div>

app/views/resumes/new.html.erb
</head>
<div class="top-margin">
	<!--display the post-->
	<div id="post" class="post_feed">
		<h2>Post my resume</h2>
		<%= form_for @resume do |f| %>
			<%= f.label :name, "Name:"%>
			<%= f.text_field :name, :class=>"width-textfield" %>

			<%= f.label :content, "Content:" %>

			<%= f.cktext_area :content, :class=>"width-textfield", :id=>"new_content" %><br>

			<%= f.label :show, "Show:" %>
			<%= f.check_box :show %><br>
			<br>
			<br>
			<br>
			<%= f.submit "Post", :confirm =>"Post?", :class => "btn btn-large btn-primary" %>
			<%= link_to "Cancel", resumes_path, :confirm =>"Give up this resume?",:class=> "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>