config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    member do
      get 'showByTag'
    end
    collection do
      post 'search'
      get 'showByMonth'
    end
  end

  match '/blog', :to=>'posts#index'
  match '/create', :to => 'posts#create'
  match '/update', :to => 'posts#update'
  match '/delete', :to => 'posts#destroy'

  resources :resumes
  resources :comments
  resources :notices
  resources :abouts, :only => [:index]

  match '/home', :to => 'abouts#index'

  resources :settings do
    collection do 
      post 'update_intro'
      post 'create_link'
      post 'update_link'
      delete 'destroy_link'
    end
  end

  
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => 'abouts#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	attr_accessible :name, :password
	has_secure_password
	before_save :create_remember_token

	private
		def create_remember_token
			self.remember_token = SecureRandom.hex 
		end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	include Rakismet::Model
	attr_accessible :author, :content, :post_id
	belongs_to :post
	has_many :notices, :dependent => :delete_all
	validates :content, :presence => true
	validates :content, :length => { :minimum => 6 }
	def my_to_json(signed)
		Jbuilder.encode do |json|
			json.current self.id
			json.count Post.find(self.post.id).comments.size
			json.valid signed
			json.saved true
			json.comments Post.find(self.post.id).comments do |comment|
				json.id comment.id
				json.author comment.author
				json.content comment.content
				json.created_at comment.created_at.to_formatted_s(:long)
				json.mine comment.mine
				json.post_id comment.post_id
			end
		end
	end
end

app/models/intro.rb
class Intro < ActiveRecord::Base
	attr_accessible :content
end

app/models/link.rb
class Link < ActiveRecord::Base
	attr_accessible :name, :url
end

app/models/notice.rb
class Notice < ActiveRecord::Base
	attr_accessible :comment_id, :active
	default_scope order('created_at DESC')
	belongs_to :comment
end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :title, :content
	has_and_belongs_to_many :tags
	has_many :comments, :dependent => :delete_all
	has_many :notices, :through => :comments

	def pre_post
		Post.where("id < ?", self.id).order("id DESC").first
	end

	def next_post
		Post.where("id > ?", self.id).order("id ASC").first
	end
end

app/models/resume.rb
class Resume < ActiveRecord::Base
	attr_accessible :name, :content, :show
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :posts
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
	layout "aboutLayout"
	def index
	end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
	before_filter :admin_validate, :only => [:index, :viewAll]

	def index
		@notices = Notice.paginate(:page => params[:page], :per_page => 20)
	end

	def show
		notice = Notice.find params[:id]
		notice.update_attributes({:active => false})
		redirect_to notice.comment.post
	end

	def viewAll

	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :admin_validate, :only => [:new, :create, :edit, :update, :destroy]
	respond_to :html, :xml, :json

	def index
		@intro = Intro.first
		@links = Link.all
		@posts = Post.paginate(:page => params[:page], :per_page => 10, :order => 'updated_at DESC')
		@posts_years = Post.all.group_by {|post| post.created_at.beginning_of_year}
	end

	def show
		@post = Post.find params[:id]
		@comment = Comment.new
	end

	def search
		@keyword = params[:keyword]
		@posts = Post.paginate(:conditions => ["content LIKE ? or title LIKE ?", "%#{@keyword}%", "%#{@keyword}%"], :page => params[:page], :per_page => 10)
	end

	def showByMonth
		@month = Date.parse params[:month]
		sql = "select *
		from posts
		where created_at >= '#{@month.beginning_of_month}' and  
		created_at < '#{@month.next_month.beginning_of_month}'
		"
		#@posts = Post.find_by_sql(sql)
		@posts = Post.paginate_by_sql(sql, :page => params[:page], :per_page => 10)
		#@posts = Post.all.select { |post| post.created_at.beginning_of_month == params[:month]}
	end

	def showByTag
		@tag = Tag.find params[:id.to_s]
		@posts = @tag.posts.paginate(:page => params[:page], :per_page => 10, :order => 'updated_at DESC')
	end

	def edit
		@post = Post.find params[:id]
		@tags = @post.tags
		@all_tags = Tag.all
	end

	def update
		post = Post.find params[:post][:id]
		if Post.update(post.id, :title => params[:post][:title], :content => params[:post][:content])
			tags = params[:post][:tags].split(/,/)
			post.tags.each do |t|
				if tags.include? t.name
					tags.delete t.name
				else
					post.tags.delete t
					if t.posts.empty?
						Tag.delete t.id
					end
				end
			end
			if tags
				tags.each do |t|
					tag = Tag.find_by_name t
					unless tag
						tag = Tag.new(:name => t)
						tag.save
					end
					post.tags<<tag
				end
			end
			flash[:success] = 'Successfully saved!'
			redirect_to post_path(post)
		else
			render 'edit'
		end
	end

	def new
		@tags = Tag.all
	end

	def create
		post = Post.new
		post.title = params[:post][:title]
		post.content = params[:post][:content]
		tags = params[:post][:tags].split(/,/)
		
		tags.each do |t|
			if !t.blank?
				tag = Tag.find_by_name t
				unless tag
					tag = Tag.new(:name => t)
					tag.save
				end
				post.tags<<tag
			end
		end
		
		if post.save
			flash[:success] = 'Successfully posted!'
			redirect_to post_path(post)
		else
			render 'new'
		end
	end

	def destroy
		id = params[:id]
		post = Post.find id
		tags = post.tags
		notices = post.notices
		notices.each do |n|
			Notice.delete n.id
		end
		tags.each do |t|
			if t.posts.size == 1
				Tag.delete t.id
			end
		end
		if post.destroy
			flash[:success] = 'Successfully deleted!'
			redirect_to posts_path
		else
			render 'destroy'
		end
	end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController

	before_filter :admin_validate, :only => [:new, :create, :edit, :update, :destroy]

	def index
		@resume = Resume.order("updated_at DESC").where(:show => "t").first()
	end

	def new
		@resume = Resume.new
	end

	def create
		resume = Resume.new(params[:resume])
		if resume.save
			flash[:success] = 'Resume successfully posted!'
			redirect_to resumes_path
		else
			render 'new'
		end
	end

	def edit
		@resume = Resume.find params[:id]
	end

	def update
		resume = Resume.find params[:id]
		if resume.update_attributes(params[:resume])
			flash[:success] = 'Successfully updated!'
			redirect_to resumes_path
		else
			render 'edit'
		end
	end

	def destroy
		if Resume.delete params[:id]
			flash[:success] = 'Successfully deleted!'
			redirect_to resumes_path
		else
			render 'destroy'
		end
	end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def client_ip
  		request.remote_ip
  	end

  	def record_ip(where)
  		if !signed_in?
  			Rails.logger.info "<record> #{client_ip} @#{Time.now} visited #{where} </record>"
  		end
  	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(admin)
		cookies.permanent[:remember_token] = admin.remember_token
		self.current_admin = admin
	end

	def current_admin=(admin)
		@current_admin = admin
	end

	def current_admin
		@current_admin ||= Admin.find_by_remember_token(cookies[:remember_token])
	end

	def signed_in?
		!current_admin.nil?
	end

	def sign_out
		self.current_admin = nil
		cookies.delete(:remember_token)
	end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/layouts/_navbar.html.erb
<!--navigate bar-->
		<div id="navbar" class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<a class="brand" href=<%= root_path %>>Xiaotong Chen</a>
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				      </a>
				    <div class="nav-collapse collapse">
						<ul class="nav">
							<li class="divider-vertical"></li>
							<li><%= link_to "HOME", home_path%></a></li>
							<li class="divider-vertical"></li>
							<li><%= link_to "BLOG", blog_path%></a></li>
							<li class="divider-vertical"></li>
							<li><%= link_to "RESUME", resumes_path%></li>
							<li class="divider-vertical"></li>
							<% if signed_in? %>
								<li id="fat-menu" class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">
										ADMIN <b class="caret"></b>
									</a>
									<ul class="dropdown-menu" >
										<li><%= link_to "Write a post", new_post_path %></li>
										<li><%= link_to "Post a resume", new_resume_path %></li>
										<li><%= link_to "Setting", settings_path %></li>
										<li><%= link_to "Notices", notices_path %></li>
										<li class="divider"></li>
										<li><%= link_to "Sign out", signout_path %></li>
									</ul>
								</li>
							<% end %>
						</ul>
						<form class="navbar-search pull-right" id="search_form" action=<%= search_posts_path %> method="post">
							<input type="text" class="search-query" placeholder="Search" id="search_box" name="keyword"/>
						</form>
					</div>
				</div>
			</div>
		</div>
<!--google analytics-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43559671-1', 'xiaotong-blog.herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/layouts/aboutLayout.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="google-site-verification" content="hMXTBwBH_WFlXloSYEL0LTIBYrDo52m7MYmoQ6gXflU" />
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Xiaotong Chen | Home</title>
  <% record_ip("home") %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
  <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
   <%= stylesheet_link_tag    "application", :media => "all" %>

</head>
<body>
		<%= render :partial => "layouts/navbar" %>
		<!--main container-->
		<%= yield %>
<script type="text/javascript">
   $(document).ready(function() {
      $('body').jpreLoader({
      	splashID: "#jSplash",
		    loaderVPos: '50%'
      });
   });
</script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="google-site-verification" content="0SZ5Rj7-NRm2tqjP_PAmKojZUff0Xqv_75H_OXDL8y0" />
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Xiaotong Chen <%= yield :title %></title>
  <% record_ip(yield :where) %>
  <script type="text/javascript">var CKEDITOR_BASEPATH = '/assets/ckeditor/';</script>
  <%= javascript_include_tag "application" %>
  <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
  <%= stylesheet_link_tag "application", :media => "all" %>
</head>
<body>
	<div class="bg">
		<!--navigate bar-->
		<%= render :partial => "layouts/navbar" %>
		<!--main container-->
		<div id="main_container" class="container">
			<% flash.each do |key, value| %>
        		<div class="alert alert-<%= key %> top-margin"><%= value %></div>
      		<% end %>
      		<!--go top-->
			<div id="go-top" class="go-top">
				<div id="go-top-img" class="go-top-img">
					
				</div>
			</div>
			<!--main display area-->
			<%= yield %>
		</div>
		<!--footer-->
		<div id="footer" class="footer">
			<p class="muted" align="center">Xiaotong Chen ©2013</p>
		</div>
	</div>
</body>
</html>